# Use postgres/example user/password credentials
version: '3.1'
services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: person
    volumes:
      - ./appdata/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - massmonitor
  app:
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USER: ${DB_USER}
      DB_URL: ${DB_URL}
      BOT_USERNAME: ${BOT_USERNAME}
      BOT_TOKEN: ${BOT_TOKEN}
    image: devp1337/massmonitor
    restart: always
    networks:
      - massmonitor
      - nginx

networks:
 massmonitor:
 nginx:
