name: Build and analyze
on:
  workflow_dispatch:
    run-name: Build and analyze
    branches:
      - main
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
permissions:
  pull-requests: read # allows SonarCloud to decorate PRs with analysis results
jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: corretto
      
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: '${{ runner.os }}-m2-${{ hashFiles(''**/pom.xml'') }}'
          restore-keys: '${{ runner.os }}-m2'
      - name: build
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        run: mvn -B package
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: devp1337/massmonitor:latest
      - name: deploy
        run: curl http://testp.de:9000/hooks/redeploy-webhook
  quality:
    runs-on: ubuntu-latest
    steps:
    - name: sonar
      uses: actions/checkout@v3
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
